"""create buyers table

Revision ID: 6248d42c07d2
Revises: 070acfc626f9
Create Date: 2024-12-20 07:48:47.617466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6248d42c07d2'
down_revision: Union[str, None] = '070acfc626f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('product_name', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('product_price', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('product_type', sa.Text(), nullable=False))
    op.drop_column('products', 'Product_price')
    op.drop_column('products', 'Product_name')
    op.drop_column('products', 'Product_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('Product_type', sa.TEXT(), nullable=False))
    op.add_column('products', sa.Column('Product_name', sa.TEXT(), nullable=False))
    op.add_column('products', sa.Column('Product_price', sa.INTEGER(), nullable=False))
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'product_price')
    op.drop_column('products', 'product_name')
    op.drop_table('Buyers')
    # ### end Alembic commands ###
